-- RUN THIS IN YOUR SUPABASE SQL EDITOR --

-- 1. Add roles array and hero_image_url to profile table
ALTER TABLE public.profile 
ADD COLUMN IF NOT EXISTS roles text[] DEFAULT ARRAY['CSE Student @ AIUB', 'Software Developer', 'Creative Designer', 'Problem Solver'],
ADD COLUMN IF NOT EXISTS hero_image_url text;

-- 2. Add whatsapp_number to contact table
ALTER TABLE public.contact 
ADD COLUMN IF NOT EXISTS whatsapp_number text DEFAULT '8801700000000';

-- (Note: No new RLS policies or Storage buckets are required as the existing "portfolio-assets" bucket covers the new image upload)

-- 3. Create Experience Table
CREATE TABLE IF NOT EXISTS public.experience (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  role text not null,
  company text not null,
  date_start text not null,
  date_end text not null,
  description text,
  sort_order integer default 0
);

-- Enable RLS for Experience
ALTER TABLE public.experience ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.experience;
CREATE POLICY "Enable read access for all users" ON public.experience FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.experience;
CREATE POLICY "Enable all access for authenticated users" ON public.experience FOR ALL USING (auth.role() = 'authenticated');

-- 4. Create Stats Table
CREATE TABLE IF NOT EXISTS public.stats (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  label text not null,
  value text not null,
  icon text,
  sort_order integer default 0
);

-- Enable RLS for Stats
ALTER TABLE public.stats ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.stats;
CREATE POLICY "Enable read access for all users" ON public.stats FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.stats;
CREATE POLICY "Enable all access for authenticated users" ON public.stats FOR ALL USING (auth.role() = 'authenticated');
